#' Create the path elements for MeteoGalicia API
#'
#' Path vectors for MeteoGalicia API to use with httr::GET
#'
#' @param api_options Option list as generated by \link{\code{meteogalicia_options}}
#'
#' @noRd
.create_meteogalicia_path <- function(api_options) {

  # we need the resolution to create the corresponding path
  resolution <- api_options$resolution
  # we need to transform the dates to the character string specific format for the meteogalicia path.
  # We will use a stamp function:
  meteogalicia_stamp <- lubridate::stamp("25-12-2001", orders = "dmY", quiet = TRUE)

  ## TODO Maybe a switch here is more efficient, but we have to control for non recognised resolution.
  ## Worth to check it some time.

  # instant
  if (resolution == 'instant') {
    return(c('rss', 'observacion', 'ultimos10minEstacionsMeteo.action'))
  }

  # current day
  if (resolution == 'current_day') {
    return(c('rss', 'observacion', 'ultimosHorariosEstacions.action'))
  }

  # daily
  if (resolution == 'daily') {
    return(c('rss', 'observacion', 'datosDiariosEstacionsMeteo.action'))
  }

  # monthly
  if (resolution == 'monthly') {
    return(c('rss', 'observacion', 'datosMesuaisEstacionsMeteo.action'))
  }

  # not recognised resolution
  stop(
    api_options$resolution,
    " is not a valid temporal resolution for MeteoGalicia. Please see meteogalicia_options help for more information"
  )
}


#' Get info for the meteogalicia stations
#'
#' Get info for the meteogalicia stations
#'
#' @noRd

.get_info_meteogalicia <- function(api_options) {
  # path
  path_resolution <- c(
    'rss', 'observacion', 'listaEstacionsMeteo.action'
  )

  # api response
  api_response <- httr::GET(
    "http://servizos.meteogalicia.es",
    path = path_resolution
  )

  # check status
  if (api_response$status_code != 200) {
    stop("Unable to connect to meteogalicia API at ", api_response$url)
  }

  response_content <- jsonlite::fromJSON(httr::content(api_response, as = 'text'))

  # Meteogalicia returns a list, with one element called listaEstacionsMeteo, that is parsed directly to
  # a data.frame with all the info. We work with that.
  response_content$listaEstacionsMeteo %>%
    dplyr::as_tibble() %>%
    dplyr::select(
      station_id = idEstacion, station_name = estacion, station_province = provincia,
      altitude, lat, lon
    ) %>%
    dplyr::mutate(
      station_id = as.character(station_id),
      altitude = units::set_units(altitude, m)
    ) %>%
    sf::st_as_sf(coords = c('lon', 'lat'), crs = 4326)

}
